### ISSUE TITLE
Files:[no files]

### ISSUE THREAD

**Issue by vchouhan** [fatso83/grunt-penthouse#10]
grunt process success and critical file generated Files:[no files]
grunt.initConfig({
        penthouse: {
            extract: {
                outfile: 'build/css/critical.css',
                css: 'build/css/spa.min.css',
                url: 'http://localhost/~vc/voSpa/build/spa.html',
                width: 1300,
                height: 900
            },
        },
})

Running "penthouse:extract" (penthouse) task
Verifying property penthouse.extract exists in config...OK
File: [no files]
Writing build/css/critical.css...OK

**Comment by pocketjoso** [comment]
This seems to be [Grunt's default behavior (expecting either src or dest to be set)](https://github.com/gruntjs/grunt/issues/657), but we're not using them for this grunt task, so you can just ignore this. It doesn't effect the output.
