### ISSUE TITLE
Add option for ignoring font-face/url 

### ISSUE THREAD

**Issue by prtk418** [fatso83/grunt-penthouse#24]
while inlining the generated css the font-face and url attributes are added which renderes wrong path in server and thus gives 404.
an option must be there to ignore such attributes.

**Comment by pocketjoso** [comment]
these paths should be correct - can you provide more details and file an issue on the core library, Penthouse, instead?

https://github.com/pocketjoso/penthouse

**Comment by prtk418** [comment]
suppose In the original minified css file the src attribute has a value of url(../../css/fonts/icomoon.eot);
after generating the critical css the styles are inlined which changes the absolute path of the fonts/images rendered via src.

Which causes a 404.
Hope this makes sense now.

**Comment by pocketjoso** [comment]
Yeah you're right, services like https://criticalcss.com (which I'm behind) take care of path rewriting for you, but when using a low level library like this you have to manage it yourself.

Not sure that ignoring would be a good option, as it would make the first render less complete. How hard would it be in your case to rewrite the paths? If you're only working on a single stylesheet it should be possible to do with a simple search+replace operation?

**Comment by prtk418** [comment]
I am using this in a production server with lots of stylesheets, actually I
solved the problem by using regex patterns, while inlining i replaced the
wrong urls with working one.
