### ISSUE TITLE
open URL with cookies

### ISSUE THREAD

**Issue by mitalgevariya** [fatso83/grunt-penthouse#26]
Hi, can we use grunt-penthhouse to get css for a URL but with some cokkies set? such as login credentials to extract critical CSS of page for loggedin users?

**Comment by pocketjoso** [comment]
Hi,

1. Note that critical css has most impact for the first visit, before the full css has been cached. Hence it's not as useful for logged in users, and generally something I do not setup for my own sites. It doesn't hurt if you add it though, it's just that you add more complexity for almost no improvement performance wise.
2. If you still want to do it, with Penthouse you can use the `customPageHeaders` or `cookies` option to do what you want. They are documented here:
https://github.com/pocketjoso/penthouse#options

**Comment by mitalgevariya** [comment]
> Hi,
> 
> 1. Note that critical css has most impact for the first visit, before the full css has been cached. Hence it's not as useful for logged in users, and generally something I do not setup for my own sites. It doesn't hurt if you add it though, it's just that you add more complexity for almost no improvement performance wise.
> 2. If you still want to do it, with Penthouse you can use the `customPageHeaders` or `cookies` option to do what you want. They are documented here:
>    https://github.com/pocketjoso/penthouse#options

Hello,
Thank you!

For option 2: does it mean I will need to crate my js to use Penthouse? Or I can add cookies option like below? 

grunt.initConfig({
  penthouse: {
    extract : {
        outfile : '.tmp/out.css',
        css : './dist/css/full.css',
        url : 'http://localhost:9000',
	cookies: ['cookieName=cookieVal;'],
        width : 1300,
        height : 900,
        skipErrors : false // this is the default
    },
  },

I am very new to grunt, Please help me out here!

**Comment by pocketjoso** [comment]
You should be able to use it with grunt, but I'm not 100% sure how, as I do not use this package anymore myself. @fatso83 do you know - are all the options inside the `extract` passed through to penthouse?

**Comment by mitalgevariya** [comment]
Hello,
Thank you very much. 
@fatso83  Please let me know if it is possible with grunt.

**Comment by fatso83** [comment]
@mitalgevariya the source code is there and is super small. You know you can just read it, right?

**Comment by fatso83** [comment]
Ok, had a look. The answer is yes, we just invoke penthouse and pass on the options. We don't parse them in any way. 
https://github.com/fatso83/grunt-penthouse/blob/master/tasks/penthouse.js
