### ISSUE TITLE
Unable to access network

### ISSUE THREAD

**Issue by nakoo** [fatso83/grunt-penthouse#7]
When I run grunt-penthouse I get the 'Done. without errors' message, but output file is written 'Unable to access network'.

Here is my config:

    penthouse: {
    	extract: {
    		css: 'build/style.min.css',
    		outfile: 'build/penthouse.css',
    		url: 'http://localhost:9000',
    		width: 1300,
    		height: 900
    	}
    },

**Comment by fatso83** [comment]
Thanks for reporting. Will look into it.

**Comment by fatso83** [comment]
Do you actually run anything on port 9000?

**Comment by fatso83** [comment]
@pocketjoso maybe you should do add some error handling for network errors? I am guessing @nakoo is experiencing penthouse trying to contact a non-existing server, but the error message should go to stderr, not stdout. And penthouse should exit with a non-zero exit code.

**Comment by fatso83** [comment]
As there hasn't been any additional info to my questions, I am closing this as non-issue.
