### ISSUE TITLE
Penthouse upgrade

### ISSUE THREAD

**Issue by roderickhsiao** [fatso83/grunt-penthouse#8]
https://github.com/pocketjoso/penthouse 

seems @pocketjoso has a new version bump, do we want to try the new penthouse package ?

Thanks

**Comment by fatso83** [comment]
Yeah, thanks for reminding me. I actually contributed to that release a lot with work dating back to July, and I just forgot that this tool has a dependency on it.

**Comment by roderickhsiao** [comment]
Thanks!
