### ISSUE TITLE
updated images path for the resulting css

### ISSUE THREAD

**Issue by vlrprbttst** [fatso83/grunt-penthouse#9]
i just noticed how penthouse spits the above-the-fold css keeping external resources urls the same as the ones in the css file.

i have a folder structure like this:

```
index.html
--css/main.css
--images/image.png
```

so my images path are like this `../images/image.png` in main.css, but should be spit out like this `images/image.png` in the above-the-fold file to be effective, as i'm inlining it in the index's `head`.

that's would be a cool feature to add for future versions of penthouse. thanks

**Comment by pocketjoso** [comment]
Penthouse doesn't know where your css is in the folder structure, so it doesn't know how to rewrite paths.

The advice given by Penthouse is to us absolute paths to avoid this.

**Comment by fatso83** [comment]
Guessing paths might be tricky, but if I added support for a replacement patterns maybe you could achieve it like this:

```
grunt.initConfig({
  penthouse: {
    extract : {
        outfile : '.tmp/out.css',
        css : './dist/css/full.css',
        url : 'http://localhost:9000',
        width : 1300,
        height : 900,
        replace : [
                {pattern: '../images', with:'/images',
                {pattern: '../fonts', with:'/fonts'}
        ]
    },
  },
});
```

Simple string substitution like that would be easy to support, but not sure how I could create a syntax for regexes (which would be more powerful).

**Comment by vlrprbttst** [comment]
yeah that would be great!

**Comment by fatso83** [comment]
Approaching a deadline atm, so I am proposing that the quickest fix is cloning the repo and adding it yourself. It's like ten lines of code. And I accept pull requests :-)

I won't have time until the week after Easter.

**Comment by vlrprbttst** [comment]
i'm new to github I'm not sure i'd the able to do that :)

**Comment by pocketjoso** [comment]
You could also just use another plugin, such as [grunt replace](https://github.com/outaTiME/grunt-replace) to do the path replacement (after running grunt-penthouse).

**Comment by fatso83** [comment]
Good tip, Jonas. That is the right way to do it, @vlrprbttst (that nick took me ages to write right!). Closing this as a wontfix.
